### ISSUE TITLE
Request mod api dev help

### ISSUE THREAD

**Issue by exdj158** [TitanPowered/Gaia#3]
How to obtaining an instance of the API on fabric?

**Comment by PrimordialMoros** [comment]
Admittedly, there's no easy way at the moment. I could add some entrypoint or global provider for it but can you help me understand your exact usecase first? What do you need it for?

**Comment by RoDingJ** [comment]
I want to visit the Arena regions api. Get arena information and teleport players to a certain point.So that I can create custom game goals based on the arena region.
Is it possible to customize the telecom port's name?The newly added points are named by numbers, which is not flexible to select.

**Comment by exdj158** [comment]
I want to visit the Arena regions api. Get arena information and teleport players to a certain point.So that I can create custom game goals based on the arena region.
Is it possible to customize the telecom port's name?The newly added points are named by numbers, which is not flexible to select.

**Comment by exdj158** [comment]
Will it support more features in the future? Just like [pvparena](https://github.com/Eredrim/pvparena/blob/1.15/doc/getting-started.md). At present, I want to try implementing some similar functions to meet my needs first.

**Comment by PrimordialMoros** [comment]
Added an api provider class that you could use in the next version (not published yet, will check if anything else is needed first).

> Will it support more features in the future?

While this is not absolute, I will say probably not. The main point is efficient reverting of a region which I am currently satisfied with. Perhaps arena is a misnomer but that's what I primarily use it for.

However, I'd be happy to expose additional API as needed for integrations such as the one you are describing.

> The newly added points are named by numbers, which is not flexible to select.

They aren't meant to replace warps nor be user-facing. The arena points are mostly for api to use (and the command is available for things like command signs/holograms and scripts) so mapping them to names is out of scope.

**Comment by exdj158** [comment]
Thank you for your support. Is it possible to add an API for customizing the teleportation point?
